#!/bin/sh

case "$1" in
    start)
        echo "Loading sysmon kernel module"
        modprobe sysmon
        ;;
    
    stop)
        echo "Unloading sysmon kernel module"
        modprobe -r sysmon
        ;;
    
    restart)
        "$0" stop
        "$0" start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
